# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-13 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_user_auth_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, max_length=100, null=True)),
                ('lon', models.FloatField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(max_length=250)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User')),
            ],
        ),
    ]
