# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('bot_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.User')),
            ],
        ),
        migrations.AlterField(
            model_name='preference',
            name='bot_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.User'),
        ),
    ]
