# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-20 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20170420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronology',
            name='bot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='bot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
