# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20170420_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
